Factor pfsetup code.

diff --git a/tools/pfsetup b/tools/pfsetup
--- a/tools/pfsetup
+++ b/tools/pfsetup
@@ -6,20 +6,63 @@ sudo easy_install pep8
 
 SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
 DOWN_DIR="$HOME/Downloads"
+SRC_DIR="$HOME/src"
 
 # TODO: Conditional download function
 # TODO: Put all file version string at top of this file
 
+# download <url> - do nothing if already downloaded
+function download {
+    FILE_PATH=$1
+    FILE="$( basename "$FILE_PATH" )"
+
+    cd $DOWN_DIR
+    if [ ! -f $FILE ]; then
+        if ! wget $FILE_PATH; then
+            echo "Failed to download $FILE_PATH"
+            exit 1
+        fi
+    fi
+}
+
+# download_zip <url> <destination directory>
+# download and unzip directory to destination
+# cd's to the unzipped directory as a side effect
+function download_zip {
+    DEST_PATH=$2
+    DEST_PARENT="$( dirname $DEST_PATH )"
+    DEST_DIR="$( basename $DEST_PATH )"
+
+    download $1
+
+    cd $DEST_PARENT
+    rm -rf $DEST_DIR
+    sudo unzip $DOWN_DIR/$FILE
+    sudo chmod -R o+rwx $DEST_DIR
+    cd $DEST_DIR
+}
+
+# download_tar <url> <destination directory>
+# download and untar directory to destination
+# cd's to the untared directory as a side effect
+function download_tar {
+    DEST_PATH=$2
+    DEST_PARENT="$( dirname $DEST_PATH )"
+    DEST_DIR="$( basename $DEST_PATH )"
+
+    download $1
+
+    cd $DEST_PARENT
+    rm -rf $DEST_DIR
+    tar -xzvf $DOWN_DIR/$FILE
+    cd $DEST_DIR
+}
+
 # Install OpenSSL
 read -p "Install Open SSL (y/n): "
 if [ "$REPLY" = "y" ]; then
-    cd $HOME/Downloads
-    wget http://www.openssl.org/source/openssl-0.9.8g.tar.gz
+    download_tar http://www.openssl.org/source/openssl-0.9.8g.tar.gz $SRC_DIR/openssl-0.9.8g
 
-    cs $HOME/src
-    tar -xzvf $HOME/Downloads/openssl-0.9.8g.tar.gz
-
-    cd openssl-0.9.8g.tar.gz
     ./config
     make
     sudo make install
@@ -28,23 +71,18 @@ fi
 # Get Python 2.5.2
 read -p "Install Python 2.5.2 (y/n): "
 if [ "$REPLY" = "y" ]; then
-    cd $HOME/Downloads
-    if [ ! -f Python-2.5.2.tgz ]; then
-        wget http://www.python.org/ftp/python/2.5.2/Python-2.5.2.tgz
-        cd $HOME/src
-        tar -xzvf $HOME/Downloads/Python-2.5.2.tgz
-    fi
+    download_tar http://www.python.org/ftp/python/2.5.2/Python-2.5.2.tgz $SRC_DIR/Python-2.5.2
 
-    cd $HOME/src/Python-2.5.2
     ./configure
-    make clean
     make
     sudo make altinstall
 fi
 
-# TODO: Install setup tools
-# http://pypi.python.org/packages/2.5/s/setuptools/setuptools-0.6c11-py2.5.egg#md5=64c94f3bf7a72a13ec83e0b24f2749b2
-# sh setuptools-0.6c11-py2.5
+read -p "Python Setup Tools (y/n): "
+if [ "$REPLY" = "y" ]; then
+    download http://pypi.python.org/packages/2.5/s/setuptools/setuptools-0.6c11-py2.5.egg
+    sh setuptools-0.6c11-py2.5.egg
+fi
 
 sudo easy_install-2.5 mock
 sudo easy_install-2.5 PIL
@@ -52,72 +90,39 @@ sudo easy_install-2.5 PIL
 # Get SSL Library not supported in native 2.5.2
 read -p "Install Python ssl Library (y/n): "
 if [ "$REPLY" = "y" ]; then
-    cd $HOME/Downloads
-    if [! -f ssl-1.15.tar.gz ]; then
-        wget http://pypi.python.org/packages/source/s/ssl/ssl-1.15.tar.gz
-        cd $HOME/src
-        tar -xzvf $HOME/Downloads/ssl-1.15.tar.gz
-    fi
+    download_tar http://pypi.python.org/packages/source/s/ssl/ssl-1.15.tar.gz $SRC_DIR/ssl-1.15
 
-    cd $HOME/src/ssl-1.15
     sudo python2.5 setup.py install
 fi
 
 # Get Django 1.1
 read -p "Install Django 1.1 (y/n): "
 if [ "$REPLY" = "y" ]; then
-    cd $DOWN_DIR
-    if [! -f Django-1.1.2.tar.gz ]; then
-        wget  http://media.djangoproject.com/releases/1.1/Django-1.1.2.tar.gz
-        cd $HOME/src
-        tar -xzvf $HOME/Downloads/Django-1.1.2.tar.gz
-    fi
+    download_tar http://media.djangoproject.com/releases/1.1/Django-1.1.2.tar.gz $SRC_DIR/Django-1.1.2
 
-    cd $HOME/src/Django-1.1.2
     sudo python2.5 setup.py install
 fi
 
-AE_PATH="http://googleappengine.googlecode.com/files"
-AE_FILE="google_appengine_1.3.8.zip"
-AE_PARENT="/usr/local"
-AE_DIR="google_appengine"
+AE_DIR="/usr/local/google_appengine"
 
 # Get AppEngine - needs to be in /usr/local for django helper to find properly?
 read -p "Install App Engine (y/n): "
 if [ "$REPLY" = "y" ]; then
-    cd $DOWN_DIR
-    if [ ! -f $AE_FILE ]; then
-        wget $AE_PATH/$AE_FILE
-    fi
-
-    cd $AE_PARENT
-    sudo rm -rf $AE_DIR
-    sudo unzip $DOWN_DIR/$AE_FILE
-    sudo chmod -R o+rx $AE_DIR
-
-    cd /usr/local/bin
+    download_zip http://googleappengine.googlecode.com/files/google_appengine_1.3.8.zip $AE_DIR
 
     # Put dev_appserver.py and appcfg.py directly into PATH
-    sudo ln -f -s /usr/local/$AE_DIR/dev_appserver.py
-    sudo ln -f -s /usr/local/$AE_DIR/appcfg.py
+    cd /usr/local/bin
+    sudo ln -f -s $AE_DIR/dev_appserver.py
+    sudo ln -f -s $AE_DIR/appcfg.py
 fi
 
 read -p "Install App Engine Helper (y/n): "
 if [ "$REPLY" = "y" ]; then
-    cd $HOME/Downloads
-    if [ ! -f appengine_helper_for_django-r105.zip ]; then
-        wget  http://google-app-engine-django.googlecode.com/files/appengine_helper_for_django-r105.zip
-    fi
+    download_zip http://google-app-engine-django.googlecode.com/files/appengine_helper_for_django-r105.zip $AE_DIR/appengine_helper_for_django
 
-    cd /usr/local
-    sudo unzip $HOME/Downloads/appengine_helper_for_django-r105.zip
-    sudo chmod -R o+rwx appengine_helper_for_django
-
-    cd appengine_helper_for_django
     patch -p1 -i $SCRIPT_DIR/aeh.patch
 
     # Remove slow or mis-behaving tests
     cd appengine_django/tests
     rm commands_test.py integration_test.py serialization_test.py
-
 fi
